{
	"version": 1737711151,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite2-sheet0.png",
		"images/maria1-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground.png",
		"images/maria2-sheet0.png",
		"images/maria3-sheet0.png",
		"images/maria4-sheet0.png",
		"images/maria5-sheet0.png",
		"images/maria6-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite-sheet3.png",
		"images/sprite-sheet4.png",
		"images/sprite-sheet5.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"media/pop 1.m4a",
		"media/pop 1.ogg",
		"media/pop 2.m4a",
		"media/pop 2.ogg",
		"media/puch 1.m4a",
		"media/puch 1.ogg",
		"media/puch 2.m4a",
		"media/puch 2.ogg",
		"media/puch 3.m4a",
		"media/puch 3.ogg",
		"media/puch 4.m4a",
		"media/puch 4.ogg",
		"media/explosion-under-snow-sfx-230505.m4a",
		"media/explosion-under-snow-sfx-230505.ogg",
		"media/mariah 1.m4a",
		"media/mariah 1.ogg",
		"media/mariah 2.m4a",
		"media/mariah 2.ogg",
		"media/mariah 3.m4a",
		"media/mariah 3.ogg",
		"media/mgwtf - mariah xmas.m4a",
		"media/mgwtf - mariah xmas.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}